// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SAN_TouchAnimation","status":true,"description":"タッチアニメーション 1.0.0\r\nタッチ時にアニメーションを表示します。","parameters":{"AnimationID":"1","Scale":"100","Opacity":"255","Valid":"OFF"}}
];
